### ISSUE TITLE
Interactive feature not working appropriately

### ISSUE THREAD

**Issue by nupurgunwant** [gautamkrishnar/socli#120] opened 2018-02-24 11:36 UTC
After running `socli -i -q <query>` ,` <any number>` : back, previous, next and open are the 4 options in the end.
"Next" is sending to the previous answer
"Previous" isn't working
"Back" is sending to the next answer
And there is no key to *exit*

**Comment by gautamkrishnar** [comment] 2018-02-24 16:06
thanks @nupurgunwant for reporting. this might be a bug. please do let me know once u had found the root cause.Assigned this to u.

**Closed** 2018-05-11 20:31 UTC
Labels: RGSOC18, bug
