### ISSUE TITLE
Unable to run tests locally

### ISSUE THREAD

**Issue by Stig124** [gautamkrishnar/socli#205] opened 2020-09-02 14:31 UTC
I can't run tests locally it prints that error :
```
Traceback (most recent call last):
  File ".\setup.py", line 9, in <module>
    longd = f.read()
  File "c:\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 12032: character maps to <undefined>
```
Here is the walkthrough to my error : 
`git clone https://github.com/gautamkrishnar/socli.git`
`cd socli`
*did a venv* (doesn't work even out of the venv)
`pip install -r requirements.txt`
`python setup.py test`
And the error is printed
I tried out of a venv, same thing happens

I rapidely googled that issue and it was related to the encoding of `README.md`, so I saved it to UTF-16LE and tests are completed successfully

**Comment by jabhishek87** [comment] 2020-09-25 14:10
I will work on this

**Comment by gautamkrishnar** [comment] 2020-09-25 19:45
@Stig124 can you please mention the platform you are running this?

**Comment by gautamkrishnar** [comment] 2020-09-27 07:57
Closing this since I am unable to reproduce this. Feel free to reopen if you are still facing this issue.

**Closed by gautamkrishnar** 2020-09-27 07:57 UTC
Labels: Hacktoberfest, help wanted, leapcode, up-for-grabs
